---
- name: Install Node.js
  hosts: localhost
  become: false
  tasks:
    - name: Install Node.js 22 via Homebrew
      homebrew:
        name: node@22
        state: present

    - name: Add Node.js to PATH if not already added
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export PATH="/home/linuxbrew/.linuxbrew/opt/node@22/bin:$PATH"'
        state: present
        create: yes
      when: ansible_distribution == 'Debian'

    - name: Verify Node.js installation
      command: node --version
      register: node_version
      changed_when: false
      failed_when: node_version.rc != 0

    - name: Display Node.js version
      debug:
        msg: "Node.js version {{ node_version.stdout }} installed successfully"
