---
- name: Install Rust
  hosts: localhost
  become: false
  tasks:
    - name: Install Rust via Homebrew
      homebrew:
        name: rust
        state: present

    - name: Add Rust to PATH if not already added
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export PATH="/home/linuxbrew/.linuxbrew/opt/rust/bin:$PATH"'
        state: present
        create: yes
      when: ansible_distribution == 'Debian'

    - name: Create .cargo directory if it doesn't exist
      file:
        path: "{{ ansible_env.HOME }}/.cargo"
        state: directory
        mode: '0755'

    - name: Add Cargo bin to PATH if not already added
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export PATH="$HOME/.cargo/bin:$PATH"'
        state: present
        create: yes
      when: ansible_distribution == 'Debian'

    - name: Verify Rust installation
      command: rustc --version
      register: rust_version
      changed_when: false
      failed_when: rust_version.rc != 0

    - name: Display Rust version
      debug:
        msg: "Rust version {{ rust_version.stdout }} installed successfully"

    - name: Verify Cargo installation
      command: cargo --version
      register: cargo_version
      changed_when: false
      failed_when: cargo_version.rc != 0

    - name: Display Cargo version
      debug:
        msg: "Cargo version {{ cargo_version.stdout }} installed successfully"
