---
- name: Install Python
  hosts: localhost
  become: false
  tasks:
    - name: Install Python 3.13 via Homebrew
      homebrew:
        name: python@3.13
        state: present

    - name: Install Python setuptools via Homebrew
      homebrew:
        name: python-setuptools
        state: present

    - name: Install Python packaging via Homebrew
      homebrew:
        name: python-packaging
        state: present

    - name: Add Python to PATH if not already added
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export PATH="/home/linuxbrew/.linuxbrew/opt/python@3.13/bin:$PATH"'
        state: present
        create: yes
      when: ansible_distribution == 'Debian'

    - name: Verify Python installation
      command: python3 --version
      register: python_version
      changed_when: false
      failed_when: python_version.rc != 0

    - name: Display Python version
      debug:
        msg: "Python version {{ python_version.stdout }} installed successfully"

    - name: Verify pip installation
      command: pip3 --version
      register: pip_version
      changed_when: false
      failed_when: pip_version.rc != 0

    - name: Display pip version
      debug:
        msg: "pip version {{ pip_version.stdout }} installed successfully"
