---
- name: Install Ruby
  hosts: localhost
  become: false
  tasks:
    - name: Install Ruby via Homebrew
      homebrew:
        name: ruby
        state: present

    - name: Add Ruby to PATH if not already added
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export PATH="/home/linuxbrew/.linuxbrew/opt/ruby/bin:$PATH"'
        state: present
        create: yes
      when: ansible_distribution == 'Debian'

    - name: Add Ruby gems bin to PATH if not already added
      lineinfile:
        path: "{{ ansible_env.HOME }}/.zshrc"
        line: 'export PATH="/home/linuxbrew/.linuxbrew/lib/ruby/gems/3.2.0/bin:$PATH"'
        state: present
        create: yes
      when: ansible_distribution == 'Debian'

    - name: Verify Ruby installation
      command: ruby --version
      register: ruby_version
      changed_when: false
      failed_when: ruby_version.rc != 0

    - name: Display Ruby version
      debug:
        msg: "Ruby version {{ ruby_version.stdout }} installed successfully"

    - name: Verify gem installation
      command: gem --version
      register: gem_version
      changed_when: false
      failed_when: gem_version.rc != 0

    - name: Display gem version
      debug:
        msg: "gem version {{ gem_version.stdout }} installed successfully"
